config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: "application#redirect_to_flights_index"
   resources :flights , only: [:index]
   resources :bookings
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departing_flights, class_name: 'Flight', foreign_key: 'from_airport_id'
 	has_many :arriving_flights, class_name: 'Flight', foreign_key: 'to_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :passengers, inverse_of: :booking
	belongs_to :flight

	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
	belongs_to :from_airport, class_name: 'Airport' 
 	belongs_to :to_airport, class_name: 'Airport'

 	 def start_formatted
    	self.start.strftime("%m/%d/%y")
     end

     def self.search(params)
     	date = Date.parse(params[:flight][:start])
     	Flight.where("to_airport_id = :to_airport_id AND from_airport_id = :from_airport_id AND start >= :start AND start <= :end" ,
     		to_airport_id: params[:flight][:to_airport_id], 
     		from_airport_id: params[:flight][:from_airport_id],
     		 start: date.midnight, end: date.end_of_day  )
     end

     
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	def redirect_to_flights_index
		redirect_to flights_url
	end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	def new
		@flight = Flight.find(params[:flight_id])
		@booking = Booking.new
        @passengers =[]
		params[:passengers].to_i.times do
			@booking.passengers.build		
		end
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			@booking.passengers.each do |p|
				PassengerMailer.with(user: p).thanking_email.deliver_now
			end
			redirect_to @booking
        else
           redirect_to new_booking_url
		end
	end

	def show 
		@booking = Booking.find(params[:id])
	end

	private 

	def booking_params
		params.require(:booking).permit(:flight_id, :passenger_id, passengers_attributes:[:name, :email])
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
	def index
		@flight = Flight.new
		@flight_options = Flight.all.map{|f|[f.start_formatted, f.start]}
		@airport_options = Airport.all.map{|a|[a.code, a.id] }
	    
	    #debugger
	    if params[:flight]
			@search = Flight.search(params)
			@booking = Booking.new
	    else
	    	@search = [] 
		end
	 
		#debugger
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<p> From <%= @flight.from_airport.code %> to <%= @flight.to_airport.code %>, starts:<%= @flight.start %> duration: <%= @flight.duration %> </p>

<%= form_for(@booking) do |f|%>
  <%= f.hidden_field :flight_id, value: @flight.id %>
     Passengers:<br> 
     <%= f.fields_for :passengers do |p| %>
     	Name: <%= p.text_field :name%> Email: <%= p.text_field :email%>
        <br>
     <% end %>
     <br>
  
  <%= f.submit "Buy" %> 
<% end %>

app/views/bookings/show.html.erb
<h1> Flight: </h1>
<p>from <%= @booking.flight.from_airport.code %> to <%= @booking.flight.to_airport.code %> at <%= @booking.flight.start %> duration <%= @booking.flight.duration %> </p>
<h2> passengers: </h2>
<% @booking.passengers.each do |p| %>
	<p>name: <%= p.name %>  email: <%= p.email %></p>
<% end %>

app/views/flights/index.html.erb
<h1>Search flight</h1>

<%= form_for(@flight ,method: :get, url: flights_path ) do |f| %>
    
    Number of passengers:
    <select name= "passengers">
    	<option value=1>1</option>
    	<option value=2>2</option>
    	<option value=3>3</option>
    	<option value=4>4</option>
    </select>
    From:<%= f.select(:from_airport_id, @airport_options) %>
    To:<%= f.select(:to_airport_id, @airport_options) %>
    Date<%= f.select(:start, @flight_options) %>
    <br>
    
	<%= f.submit "Search" %>
<% end %>
 <br>
  <br>

<% if @search.any? %>
	<%= form_for(@booking, method: :get, url: new_booking_path )do |f|%>
		<input name="passengers" type="hidden" value="<%= params[:passengers] %>" >
		<% @search.each do |flight| %>
			From <%= flight.from_airport.code %> to <%= flight.to_airport.code %>, starts:<%= flight.start %> duration: <%= flight.duration %> <input type="radio" name="flight_id" value="<%= flight.id%>">
			<br>
		<% end %>
	    <br>
		<%= f.submit "Buy" %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>